networks:
  energy_net:


services:
  ocr-service:
    build: backend
    env_file:
      - ./.env
    depends_on:
      - db
    container_name: ocr-backend
    networks:
      - energy_net
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/app/src
      - ./backend/src/uploads:/app/src/uploads
    environment:
      - TESSDATA_PREFIX=/usr/share/tesseract-ocr/5/tessdata
    restart: always

  db:
    image: postgres:15
    restart: always
    container_name: EnergyDb
    env_file:
      - .env
    networks:
      - energy_net
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
